'use client';
import './globals.css';
// import './sidebars.css';
import { Inter } from 'next/font/google';
import Sidebar from './sidebar';
import { useRouter } from 'next/navigation';


const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };


export default function RootLayout({ children }) {
  const router = useRouter();
  // const showHeader = router.pathname === '/users/login' && router.pathname === '/users/signup';
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <section className="main">
          {children}
        </section>
      </body>
    </html>
  );
}
